// Copyright (c) 2026 vectorless developers
// SPDX-License-Identifier: MIT OR Apache-2.0

//! Tree node structure for document indexing.

use std::{cell::RefCell, rc::Rc};

/// A node in the document tree.
///
/// Each branch is a section and each leaf contains the actual text.
/// When a question is asked, an LLM navigates this tree level by level
/// to find the right answer.
#[derive(Debug, Clone)]
pub struct PageNode {
    /// Title of this section/page.
    pub title: String,

    /// Raw text content (populated at leaves).
    pub content: String,

    /// Generated by LLM, populated by indexer.
    pub summary: String,

    /// Depth in tree: 0 = root, 1 = section, 2 = subsection, etc.
    pub depth: usize,

    /// Child nodes.
    pub children: Vec<PageNodeRef>,

    /// Parent node reference.
    pub parent: Option<PageNodeRef>,

    /// Starting page number (1-based, if applicable).
    pub start_page: Option<usize>,

    /// Ending page number (1-based, if applicable).
    pub end_page: Option<usize>,

    /// Unique node identifier (e.g., "0001", "0002").
    pub node_id: Option<String>,

    /// Physical index marker (e.g., "<physical_index_5>").
    pub physical_index: Option<String>,
}

/// Reference type for `PageNode` allowing tree navigation.
pub type PageNodeRef = Rc<RefCell<PageNode>>;

impl PageNode {
    /// Create a new leaf node.
    pub fn new(title: impl Into<String>, content: impl Into<String>) -> PageNodeRef {
        Rc::new(RefCell::new(Self {
            title: title.into(),
            content: content.into(),
            summary: String::new(),
            depth: 0,
            children: Vec::new(),
            parent: None,
            start_page: None,
            end_page: None,
            node_id: None,
            physical_index: None,
        }))
    }

    /// Create a new node with a summary.
    pub fn with_summary(title: impl Into<String>, content: impl Into<String>, summary: impl Into<String>) -> PageNodeRef {
        let node = Self::new(title, content);
        node.borrow_mut().summary = summary.into();
        node
    }

    /// Create a new node with page boundaries.
    pub fn with_pages(
        title: impl Into<String>,
        content: impl Into<String>,
        start_page: usize,
        end_page: usize,
    ) -> PageNodeRef {
        let node = Self::new(title, content);
        {
            let mut borrowed = node.borrow_mut();
            borrowed.start_page = Some(start_page);
            borrowed.end_page = Some(end_page);
        }
        node
    }

    /// Check if this is a leaf node (no children).
    pub fn is_leaf(&self) -> bool {
        self.children.is_empty()
    }

    /// Get all leaf nodes under this node.
    pub fn leaves(&self) -> Vec<PageNodeRef> {
        let mut leaves = Vec::new();
        self.collect_leaves(&mut leaves);
        leaves
    }

    fn collect_leaves(&self, out: &mut Vec<PageNodeRef>) {
        if self.is_leaf() {
            // This would need a reference to self, which is complex here
            // Typically handled by tree builder which maintains references
        } else {
            for child in &self.children {
                let borrowed = child.borrow();
                borrowed.collect_leaves(out);
            }
        }
    }

    /// Get all nodes within a specific page range.
    pub fn nodes_in_page_range(&self, start: usize, end: usize) -> Vec<PageNodeRef> {
        let mut result = Vec::new();
        self.collect_nodes_in_range(start, end, &mut result);
        result
    }

    fn collect_nodes_in_range(&self, start: usize, end: usize, out: &mut Vec<PageNodeRef>) {
        // Check if this node intersects with the range
        let intersects = match (self.start_page, self.end_page) {
            (Some(node_start), Some(node_end)) => {
                node_start <= end && node_end >= start
            }
            _ => true, // No page info, include it
        };

        if intersects {
            // Would need to add self to out, but that requires a reference
            // This is typically handled by the caller
        }

        for child in &self.children {
            let borrowed = child.borrow();
            borrowed.collect_nodes_in_range(start, end, out);
        }
    }

    /// Count total nodes in this subtree.
    pub fn count_nodes(&self) -> usize {
        let mut count = 1; // Count self
        for child in &self.children {
            let borrowed = child.borrow();
            count += borrowed.count_nodes();
        }
        count
    }

    /// Get node depth.
    pub fn get_depth(&self) -> usize {
        self.depth
    }
}

/// Extension methods for PageNodeRef.
pub trait PageNodeRefExt {
    /// Set page boundaries for this node.
    fn set_page_boundaries(&self, start: usize, end: usize);

    /// Get the page range for this node.
    fn page_range(&self) -> Option<(usize, usize)>;

    /// Check if this node contains a specific page.
    fn contains_page(&self, page: usize) -> bool;

    /// Set the node ID.
    fn set_node_id(&self, id: impl Into<String>);

    /// Set the physical index marker.
    fn set_physical_index(&self, index: impl Into<String>);

    /// Add a child node.
    fn add_child(&self, child: PageNodeRef);

    /// Add a child node with page boundaries.
    fn add_child_with_pages(&self, child: PageNodeRef, start_page: usize, end_page: usize);
}

impl PageNodeRefExt for PageNodeRef {
    fn set_page_boundaries(&self, start: usize, end: usize) {
        let mut borrowed = self.borrow_mut();
        borrowed.start_page = Some(start);
        borrowed.end_page = Some(end);
    }

    fn page_range(&self) -> Option<(usize, usize)> {
        let borrowed = self.borrow();
        match (borrowed.start_page, borrowed.end_page) {
            (Some(start), Some(end)) => Some((start, end)),
            _ => None,
        }
    }

    fn contains_page(&self, page: usize) -> bool {
        if let Some((start, end)) = self.page_range() {
            page >= start && page <= end
        } else {
            false
        }
    }

    fn set_node_id(&self, id: impl Into<String>) {
        self.borrow_mut().node_id = Some(id.into());
    }

    fn set_physical_index(&self, index: impl Into<String>) {
        self.borrow_mut().physical_index = Some(index.into());
    }

    fn add_child(&self, child: PageNodeRef) {
        {
            let mut borrowed = self.borrow_mut();
            let parent_depth = borrowed.depth;
            borrowed.children.push(child.clone());
            drop(borrowed);

            let mut child_borrowed = child.borrow_mut();
            child_borrowed.depth = parent_depth + 1;
            child_borrowed.parent = Some(self.clone());
        }
    }

    fn add_child_with_pages(&self, child: PageNodeRef, start_page: usize, end_page: usize) {
        {
            let mut borrowed = self.borrow_mut();
            let parent_depth = borrowed.depth;
            borrowed.children.push(child.clone());
            drop(borrowed);

            let mut child_borrowed = child.borrow_mut();
            child_borrowed.depth = parent_depth + 1;
            child_borrowed.start_page = Some(start_page);
            child_borrowed.end_page = Some(end_page);
            child_borrowed.parent = Some(self.clone());
        }
    }
}
