// Copyright (c) 2026 vectorless developers
// SPDX-License-Identifier: MIT OR Apache-2.0

//! Tree node structure for document indexing.

use std::{cell::RefCell, rc::Rc};

/// A node in the document tree.
///
/// Each branch is a section and each leaf contains the actual text.
/// When a question is asked, an LLM navigates this tree level by level
/// to find the right answer.
#[derive(Debug, Clone)]
pub struct PageNode {
    /// Title of this section/page.
    pub title: String,

    /// Raw text content (populated at leaves).
    pub content: String,

    /// Generated by LLM, populated by indexer.
    pub summary: String,

    /// Depth in tree: 0 = root, 1 = section, 2 = subsection, etc.
    pub depth: usize,

    /// Child nodes.
    pub children: Vec<PageNodeRef>,

    /// Parent node reference.
    pub parent: Option<PageNodeRef>,
}

/// Reference type for `PageNode` allowing tree navigation.
pub type PageNodeRef = Rc<RefCell<PageNode>>;

impl PageNode {
    /// Create a new leaf node.
    pub fn new(title: impl Into<String>, content: impl Into<String>) -> PageNodeRef {
        Rc::new(RefCell::new(Self {
            title: title.into(),
            content: content.into(),
            summary: String::new(),
            depth: 0,
            children: Vec::new(),
            parent: None,
        }))
    }

    /// Create a new node with a summary.
    pub fn with_summary(title: impl Into<String>, content: impl Into<String>, summary: impl Into<String>) -> PageNodeRef {
        let node = Self::new(title, content);
        node.borrow_mut().summary = summary.into();
        node
    }

    /// Add a child node.
    pub fn add_child(&mut self, child: PageNodeRef) {
        child.borrow_mut().depth = self.depth + 1;
        child.borrow_mut().parent = Some(Rc::clone(
            &self.parent.as_ref().map(|p| Rc::clone(p)).unwrap_or_else(|| {
                // Try to find self reference - this is handled by the caller
                // typically the tree builder maintains the root reference
                Rc::new(RefCell::new(self.clone()))
            })
        ));
        self.children.push(child);
    }

    /// Check if this is a leaf node (no children).
    pub fn is_leaf(&self) -> bool {
        self.children.is_empty()
    }

    /// Get all leaf nodes under this node.
    pub fn leaves(&self) -> Vec<PageNodeRef> {
        let mut leaves = Vec::new();
        self.collect_leaves(&mut leaves);
        leaves
    }

    fn collect_leaves(&self, out: &mut Vec<PageNodeRef>) {
        if self.is_leaf() {
            // Return self as a leaf - but we need the reference
            // This is handled by the tree builder typically
        } else {
            for child in &self.children {
                child.borrow().collect_leaves(out);
            }
        }
    }
}
